var data = [ { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: 'd9b884d6-7b27-400f-aa4a-74de138804cd',
       first_name: null,
       last_name: null,
       email: 'tetonkindred@msn.com' },
    payment: null,
    votes: { count: 1, score: 0, average: 0 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4354168/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4354168/form',
       count: 12,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4354168',
    submission_id: 4354168,
    date_created: '2015-08-06T17:14:01.413',
    title: '0001',
    submission_content: null,
    status: 'In-Progress',
    is_archived: false },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: 'f3e674e0-c036-4af9-a986-2cb476881dff',
       first_name: 'David',
       last_name: 'White',
       email: 'd228m3286w@gmail.com' },
    payment: null,
    votes: { count: 3, score: 3, average: 1 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4354178/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4354178/form',
       count: 13,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4354178',
    submission_id: 4354178,
    date_created: '2015-08-06T17:18:40.117',
    title: '0002',
    submission_content: null,
    status: 'Accepted',
    is_archived: false },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: 'f916f30f-caa8-4456-94ce-c6140970541e',
       first_name: 'edward',
       last_name: 'weymouth',
       email: 'ed42311@gmail.com' },
    payment: null,
    votes: { count: 2, score: 1, average: 0.5 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4354205/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4354205/form',
       count: 11,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4354205',
    submission_id: 4354205,
    date_created: '2015-08-06T17:28:49.07',
    title: '0003',
    submission_content: null,
    status: 'Accepted',
    is_archived: false },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: '2702b020-0b6b-45c0-8418-32c635495753',
       first_name: 'PJ',
       last_name: 'Gladen',
       email: 'pjgladen@gmail.com' },
    payment: null,
    votes: null,
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4356635/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4356635/form',
       count: 16,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4356635',
    submission_id: 4356635,
    date_created: '2015-08-07T12:58:07',
    title: '0004',
    submission_content: null,
    status: 'New',
    is_archived: true },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: 'fb9f2b67-8d4d-462c-9e9d-d909f8151b94',
       first_name: 'Louis',
       last_name: 'Fontana',
       email: 'loufontana@gmail.com' },
    payment: null,
    votes: { count: 1, score: 0, average: 0 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4356740/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4356740/form',
       count: 13,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4356740',
    submission_id: 4356740,
    date_created: '2015-08-07T13:23:41.293',
    title: '0005',
    submission_content: null,
    status: 'Accepted',
    is_archived: true },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: '76c4b33f-68ec-4d52-914a-d63c03ac00da',
       first_name: 'Juniper',
       last_name: 'Chapman',
       email: 'junipie@gmail.com' },
    payment: null,
    votes: { count: 3, score: 3, average: 1 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4358195/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4358195/form',
       count: 17,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4358195',
    submission_id: 4358195,
    date_created: '2015-08-07T20:04:13',
    title: '0006',
    submission_content: null,
    status: 'Accepted',
    is_archived: false },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: 'f0d2d2a1-dce2-489f-b9e7-a9553967104a',
       first_name: 'Beth',
       last_name: 'Thomas',
       email: 'bethdianethomas@yahoo.com' },
    payment: null,
    votes: { count: 3, score: 3, average: 1 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4376206/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4376206/form',
       count: 17,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4376206',
    submission_id: 4376206,
    date_created: '2015-08-13T02:10:52',
    title: '0007',
    submission_content: null,
    status: 'Accepted',
    is_archived: false },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: 'f41f8196-3e23-4abb-8c37-ed849f68cda0',
       first_name: 'Joshua',
       last_name: 'Koerner',
       email: 'Jjkoernermusic@gmail.com' },
    payment: null,
    votes: { count: 2, score: 2, average: 1 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4376224/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4376224/form',
       count: 14,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4376224',
    submission_id: 4376224,
    date_created: '2015-08-13T02:29:37',
    title: '0008',
    submission_content: null,
    status: 'Accepted',
    is_archived: false },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: 'db5fce87-f26f-4c24-a16e-97152079808a',
       first_name: 'Abhishek',
       last_name: 'Dodda',
       email: 'abhishek.dodda1@gmail.com' },
    payment: null,
    votes: { count: 1, score: -1, average: -1 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4379533/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4379533/form',
       count: 15,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4379533',
    submission_id: 4379533,
    date_created: '2015-08-13T23:02:02',
    title: '0009',
    submission_content: null,
    status: 'Declined',
    is_archived: true },
  { category:
     { url: '/v1/categories/45715',
       category_id: 45715,
       name: 'Admission Application',
       description: null,
       blind_level: null,
       blind_value: 0 },
    submitter:
     { user_id: 'cb968e2c-afda-437b-a8ea-76e22b1bd294',
       first_name: 'Zachary',
       last_name: 'Falen',
       email: 'zach.falen@partnerscreative.com' },
    payment: null,
    votes: { count: 3, score: 3, average: 1 },
    assignments:
     { type: 'assignment',
       url: '/v1/submissions/4381177/assignments',
       count: 1,
       items: [Object] },
    labels: null,
    form:
     { type: 'form',
       url: '/v1/submissions/4381177/form',
       count: 15,
       items: [Object] },
    files: [],
    url: '/v1/submissions/4381177',
    submission_id: 4381177,
    date_created: '2015-08-14T12:33:57',
    title: '0010',
    submission_content: null,
    status: 'In-Progress',
    is_archived: false } ]

    for (var i = 0; i < data.length; i++) {
      console.log(data[i].submitter)
    };

    console.log(data.length + "THIS MANY ITEMS");
    console.log(data[3].submitter);